This is makeindex, version 2.15 [MiKTeX 2.9 64-bit] (kpathsea + Thai support).
Scanning style file D:/03_DocMASE/05_Reports/Report_01_rve_model_definition/Report01.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file Report01.acn....done (54 entries accepted, 0 rejected).
Sorting entries....done (351 comparisons).
Generating output file Report01.acr....done (39 lines written, 0 warnings).
Output written in Report01.acr.
Transcript written in Report01.alg.
