This is makeindex, version 2.15 [MiKTeX 2.9 64-bit] (kpathsea + Thai support).
Scanning style file D:/DocMASE/05_Reports/Report_02_course_proposal/report02.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file report02.acn....done (36 entries accepted, 0 rejected).
Sorting entries....done (183 comparisons).
Generating output file report02.acr....done (26 lines written, 0 warnings).
Output written in report02.acr.
Transcript written in report02.alg.
