# Autogenerated with SMOP 
from smop.core import *
# 

    clear('all')
    close_('all')
    clc
    matDbfolder='D:\\OneDrive\\01_Luca\\07_DocMASE\\07_Data\\02_Material-Properties'
    projectName=rve_mesh_create_project('VL4FC-2DmmTPL-IC-1-1-1-1-1-0-1-1-1-0-1-0-1-0.6-0.6-30-10-0-0-0.01-1-1-1-1-0.5-0.782107-1.05-20-20-20-20-20-20-6921.-6800.','D:\\OneDrive\\01_Luca\\07_DocMASE\\07_Data\\03_FEM',matDbfolder,'projectsIndex',1,1,1,0,0,0,1,1,1,0,1,0,1,0.6,0.6,30,10,0,0,0.01,1,1,1,1,cat([1000000.0],[1.0],[1.0],[1.0],[1.0],[1.0],[1.0],[1e-18],[1e-06],[1.0],[1.0],[1.0],[1.0],[1e-12],[1000000.0]),0.5,0.782107,1.05,20,20,20,20,20,20,6921.0,6800.0)
    disp(projectName)